name: TOKYOWeather

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update Scratch weather
        env:
          SCRATCH_USERNAME: ${{ secrets.SCRATCH_USERNAME }}
          SCRATCH_SESSION_ID: ${{ secrets.SCRATCH_SESSION_ID }}
          SCRATCH_PROJECT_ID: ${{ secrets.SCRATCH_PROJECT_ID }}
        run: |
          python weather.py